[package]
name = "mpv-ipc"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.89"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.44.2", features = ["full"] }
tokio-util = "0.7"
